MAIN_USER_PASSWORD = "junk"
MAIN_USER_NAME = 'test_admin'

VERIFICATION_CODE = "123456"

UNVERIFIED_USER_PASSWORD = "junk"
UNVERIFIED_USER_NAME = "unverified"
UNVERIFIED_USER_EMAIL = "verify@aol.com"

CREATE_USER_PASSWORD = "X9x^5#pXBhC["
CREATE_USER_NAME = "created_user"
CREATE_USER_EMAIL = "create@aol.com"

APP_URL = "http://localhost:47863"