APP_NAME = 'Hydra'

PRIVATE_KEY = None
MAIL = None
VERIFIED_ACCOUNT = 1
UNVERIFIED_ACCOUNT = 0

USER_EMAIL_COL = 3
USER_NAME_COL = 1
USER_ID_COL = 0
USER_TYPE_COL = 4
USER_PASSPHRASE_COL = 2
USER_IS_VERIFIED_COL = 5
USER_VERIFICATION_CODE_COL = 6
USER_IS_ACTIVE_COL = 7

RESULT_OK = 200
RESULT_INVALID_REQUEST = 400
RESULT_UNVERIFIED_ACCOUNT = 401
RESULT_FORBIDDEN = 403
RESULT_SERVER_ERROR = 500